name: opticash_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_animate: any
  flutter_hooks: any
  http: ^1.1.0
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/jpegs/
    - assets/images/svgs/

  fonts:
    - family: Rogerex
      fonts:
        - asset: assets/fonts/Rogerex/RogerexRegular.ttf
          weight: 300
        - asset: assets/fonts/Rogerex/RogerexMedium.ttf
          weight: 400
        - asset: assets/fonts/Rogerex/RogerexBlack.ttf
          weight: 500
        - asset: assets/fonts/Rogerex/RogerexSemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rogerex/RogerexBold.ttf
          weight: 700
        - asset: assets/fonts/Rogerex/RogerexMax.ttf
          weight: 800
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 800
